# Generated by Django 4.2.2 on 2023-10-11 13:16

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='imagem',
            field=models.FileField(default=None, null=True, upload_to=accounts.models.safe_rename),
        ),
    ]
